### YamlMime:ManagedReference
apiRules:
    - exclude:
          uidRegex: ^NUnit
    - exclude:
          uidRegex: ^System
    - exclude:
          uidRegex: ^UnityEngine
    - exclude:
          uidRegex: ^Microsoft
